### ISSUE TITLE
Add a Values structured field

### ISSUE THREAD

**Issue by gbonnefille** [k3s-io/helm-controller#140]
Currently, in order to pass values to `HelmChart` or `HelmChartConfig`, we have to use the `ValuesContent` field. This field is a string, generally used as a block:

```YAML
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: myapp
  namespace: kube-system
spec:
  valuesContent: |-
    ingress:
      enabled: true
```

Having a `Values` structured field would be much more usefull as we will be able to play with kustomize to patch subparts of this field in overlays.

```YAML
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: myapp
  namespace: kube-system
spec:
  values:
    ingress:
      enabled: true
```
