### ISSUE TITLE
Support for automated upgrade ?

### ISSUE THREAD

**Issue by tcoupin** [k3s-io/helm-controller#166]
Hi!

Helm-controller deploys rancher on my rke2 k8s with following manifest:

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  chart: rancher
  targetNamespace: cattle-system
  repo: https://releases.rancher.com/server-charts/stable
  valuesContent: |
    hostname: "xxxxx"
    ingress:
      tls:
        source: "secret"
        secretName: "xxxx"
```
I do not specify any version of chart. Does the controller check regularly the repo for new version to upgrade the release ?
