### ISSUE TITLE
Any --set-file option in HelmChart Resource?

### ISSUE THREAD

**Issue by kenho811** [k3s-io/helm-controller#173]
Hi,

The Helm CLI has the option to pass file content to the values.yaml via the flag --set-file.

![Screenshot_20230210_140711_Chrome.jpg](https://user-images.githubusercontent.com/57944769/218015618-f48fc565-c972-40df-a363-7ec3cd0b0d06.jpg)

Ref: 
https://v2.helm.sh/docs/using_helm/#the-format-and-limitations-of-set

Can we do something like this below using k3s's HelmChart resource?

```

apiVersion: helm.cattle.io/v1 
kind: HelmChart
metadata: 
  name: example-helmchart namespace: kube-system

 spec: 
   chart: test-helmchart     
  targetNamespace: test-namespace version: 0.0.1
  repo: https://example.com/helm-charts 
set: 
key1: "value1"
 key2: "value2" 
set-file:
 key3: "path-to-file"


```
(Sorry about the formatting. Was typing using my mobile phone)

I am mainly interested in the set-file section above.

Thank you ;))
