### ISSUE TITLE
FR: Add `spec.values` to the HelmChart CRD for structured YAML support

### ISSUE THREAD

**Issue by aofei** [k3s-io/helm-controller#218]
## Introduction

Currently, the HelmChart CRD supports specifying Chart values via `spec.valuesContent` as a raw string. While effective, this method lacks the ability to leverage YAML syntax checking when editing manifests with editors. This proposal suggests an enhancement to the HelmChart CRD to address this limitation.

The primary goal of this proposal is to introduce a new field, `spec.values`, to the HelmChart CRD. This field will allow users to provide Chart values as a YAML document rather than a raw string. This enhancement aims to improve the user experience by enabling YAML syntax validation during the editing process.

### 1. Introduction of `spec.values`

Add a new field `spec.values` to the HelmChart CRD. This field should accept a YAML document representing the Chart values.

### 2. Precedence rule

In cases where both `spec.values` and `spec.valuesContent` are provided, `spec.valuesContent` will take precedence (just like `spec.chart` and `spec.chartContent`). This ensures backward compatibility and provides flexibility for users who prefer the raw string format.

### 3. Implementation

Perhaps introduce a new field `Values` to the [pkg/apis/helm.cattle.io/v1. HelmChartSpec](https://github.com/k3s-io/helm-controller/blob/f9103f66197ade3a06f4d48c9ea85f48d8c1ff1e/pkg/apis/helm.cattle.io/v1/types.go#L21C6-L21C19) struct:

```go
import "encoding/json"

type HelmChartSpec struct {
	// ...
	Values *json.RawMessage `json:"values,omitempty"`
}
```

**Comment by brandond** [comment]
> this method lacks the ability to leverage YAML syntax checking when editing manifests with editors
> `Values *json.RawMessage `json:"values,omitempty"``

How is this handled in the generated OpenAPI spec? What specific editors handle this field type, and how does validation occur?

**Comment by tdemin** [comment]
+1. This would be particularly useful when using Kustomize to generate/override complex host/cluster-specific configurations (it can merge YAML documents, but not strings containing YAML). The existing CRDs only cover up to two levels of YAML-level merging, at `HelmChart.spec.valuesContent` and `HelmChartConfig.spec.valuesContent` respectively.

One more thing: this should apply not just to `helm.cattle.io/v1.HelmChart` but to `HelmChartConfig` too.

**Comment by brandond** [comment]
Can Kustomize merge arbitrary yaml, or does it need the document to have an OpenAPI Spec? If it requires a spec to know how to handle merging, then just changing it to `json.RawMessage` won't improve anything, as the values does not have a fixed schema.

**Comment by tdemin** [comment]
@brandond Kustomize can merge arbitrary YAML, provided it's YAML, and not a string. While having specs [improves strategic merge](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/#patching-custom-resources) for complex cases, it is no way necessary and Kustomize will happily do without it.

**Comment by aofei** [comment]
> How is this handled in the generated OpenAPI spec?

Yeah, I was wrong. `json.RawMessage` will be represented as a `string` type in the generated OpenAPI spec:

<details><summary>helmcharts.helm.cattle.io</summary>

```yaml
spec:
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              type: object
              properties:
                values:
                  nullable: true
                  type: string
```

</details> 

Referring to [this](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#rawextension), it seems that `HelmChartSpec.Values` should be of type [`runtime.RawExtension`](https://pkg.go.dev/k8s.io/apimachinery/pkg/runtime#RawExtension). However, I don't know how to set `x-kubernetes-preserve-unknown-fields: true` for it.

> What specific editors handle this field type, and how does that enhance the display and validation of the resource as a whole?

Actually my motivation stemmed from a YAML syntax error in `spec.valuesContent` that I overlooked, as raw string values lacked syntax checking. So all I want initially was basic YAML syntax checking and highlighting. But @tdemin came up with something more interesting.

**Comment by brandond** [comment]
I'm not sure there is an unstructured type that will get you exactly what you want. Can you provide an example of another customer resource definition that does what you want in your editor of choice?

**Comment by aofei** [comment]
Cert-manager has something similar. Their [webhook `Issuer`](https://cert-manager.io/docs/configuration/acme/dns01/webhook/) has a `config` field that supports arbitrary YAML. But instead of using `runtime.RawExtension`, it uses [`k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1.JSON`](https://pkg.go.dev/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1#JSON).

I believe this is what we want as `x-kubernetes-preserve-unknown-fields: true` will be added automatically.

```go
import apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"

type HelmChartSpec struct {
	// ...
	Values *apiextensionsv1.JSON `json:"values,omitempty"`
}
```

```yaml
spec:
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              type: object
              properties:
                values:
                  nullable: true
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
```

**Comment by tdemin** [comment]
ArgoCD does it [like that](https://github.com/argoproj/argo-cd/blob/b12630c4be3dc73bc89eb5295ef3a582c7ae628b/manifests/crds/application-crd.yaml#L3064) for their `argoproj.io/v1alpha1.Application.spec.source.helm.valuesObject` (and a multitude of fields elsewhere):

```yaml
                                    valuesObject:
                                      description: ValuesObject specifies Helm values
                                        to be passed to helm template, defined as
                                        a map. This takes precedence over Values.
                                      type: object
                                      x-kubernetes-preserve-unknown-fields: true
```

They [seem to be using](https://github.com/argoproj/argo-cd/blob/b12630c4be3dc73bc89eb5295ef3a582c7ae628b/pkg/apis/application/v1alpha1/types.go#L323) `*runtime.RawExtension`:

```go
type ApplicationSourceHelm struct {
...
	// ValuesObject specifies Helm values to be passed to helm template, defined as a map. This takes precedence over Values.
	// +kubebuilder:pruning:PreserveUnknownFields
	ValuesObject *runtime.RawExtension `json:"valuesObject,omitempty" protobuf:"bytes,10,opt,name=valuesObject"`
}
```
