### ISSUE TITLE
Invalid chart name on install

### ISSUE THREAD

**Issue by vertisan** [k3s-io/helm-controller#231]
It seems the chart name for the `helm` command is generated improperly.

Generated command:
```shell
helm_v3 install --namespace argocd --create-namespace --version 6.7.2 argocd argocd/argo/argo-cd --values /config/values-01_HelmChart.yaml 
```
Expected command:
```shell
helm_v3 install --namespace argocd --create-namespace --version 6.7.2 argocd argo/argo-cd --values /config/values-01_HelmChart.yaml 
```

Used `HelmChart`:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
spec:
  repo: https://argoproj.github.io/argo-helm
  createNamespace: true
  chart: argo/argo-cd
  version: 6.7.2
  targetNamespace: argocd
  valuesContent: |-
    global:
      domain: argocd.example.com
    controller:
      resources:
        limits:
          cpu: 500m
          memory: 300Mi
    server:
      ingress:
        enabled: true
        tls: true
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      certificate:
        enabled: true
        issuer:
          name: 'letsencrypt-prod'
          kind: 'ClusterIssuer'
    notifications:
      enabled: false
```

Logs:
```
+ CHART_PATH=/tmp/argocd.tgz                                                                                                                                                                                                                  + [[ ! -f /chart/argocd.tgz.base64 ]]                                                                                                                                                                                                         + return                                                                                                                                                                                                                                      + [[ install != \d\e\l\e\t\e ]]                                                                                                                                                                                                               + helm_repo_init                                                                                                                                                                                                                              + grep -q -e 'https\?://'                                                                                                                                                                                                                     + [[ helm_v3 == \h\e\l\m\_\v\3 ]]                                                                                                                                                                                                             + [[ argocd/argo/argo-cd == stable/* ]]                                                                                                                                                                                                       + [[ -n https://argoproj.github.io/argo-helm ]]                                                                                                                                                                                               + [[ -f /auth/username ]]                                                                                                                                                                                                                     + helm_v3 repo add argocd https://argoproj.github.io/argo-helm                                                                                                                                                                                "argocd" already exists with the same configuration, skipping                                                                                                                                                                                 + helm_v3 repo update                                                                                                                                                                                                                         Hang tight while we grab the latest from your chart repositories...                                                                                                                                                                           ...Successfully got an update from the "argocd" chart repository                                                                                                                                                                              Update Complete. ⎈Happy Helming!⎈                                                                                                                                                                                                             + helm_update install --namespace argocd --create-namespace --version 6.7.2                                                                                                                                                                   + [[ helm_v3 == \h\e\l\m\_\v\3 ]]                                                                                                                                                                                                             ++ helm_v3 ls --all -f ++ tr '' ''
'^argocd$' --namespace argocd --output json
++ jq -r '"\(.[0].app_version),\(.[0].status)"'
+ LINE=null,null
+ IFS=,
+ read -r INSTALLED_VERSION STATUS _
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml'
+ [[ install = \d\e\l\e\t\e ]]
+ [[ null =~ ^(|null)$ ]]
+ [[ null =~ ^(|null)$ ]]
+ echo 'Installing helm_v3 chart'
+ helm_v3 install --namespace argocd --create-namespace --version 6.7.2 argocd argocd/argo/argo-cd --values /config/values-01_HelmChart.yaml
Error: INSTALLATION FAILED: chart "argo/argo-cd" matching 6.7.2 not found in argocd index. (try 'helm repo update'): no chart name found
```
