### ISSUE TITLE
Unable to install large Helm Chart using `chartContent`

### ISSUE THREAD

**Issue by koendelaat** [k3s-io/helm-controller#267]
## Use-case:

- Create a HelmChart CR for kube-prometheus-stack, with the chart captured in the `chartContent` field.
- Apply this manifest to Kubernetes (k3s) cluster

### Expected result:

- helm-install-kube-prometheus-stack job is created
- chart-content-kube-prometheus-stack configmap is created
- job succeeds and kube-prometheus-stack is installed

### Actual result:
- helm-install-kube-prometheus-stack job is created
- chart-content-kube-prometheus-stack configmap is **NOT** created
- job remains pending with message: `MountVolume.SetUp failed for volume "content" : configmap "chart-content-kube-prometheus-stack" not found`

Journalctl logs show:
```
Mar 12 15:57:48 my-hostname k3s[3731]: time="2025-03-12T15:57:48Z" level=error msg="error syncing 'kube-system/kube-prometheus-stack': handler helm-controller-chart-registration: failed to create kube-system/chart-content-kube-prometheus-stack /v1, Kind=ConfigMap for helm-controller-chart-registration kube-system/kube-prometheus-stack: ConfigMap \"chart-content-kube-prometheus-stack\" is invalid: []: Too long: must have at most 1048576 bytes, requeuing" 
```

Used chart:
```yaml
repository: https://prometheus-community.github.io/helm-charts
chart: kube-prometheus-stack
version: 69.8.2
```

<details>

<summary>HelmChart/kube-prometheus-stack</summary>

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-prometheus-stack
  namespace: kube-system
spec:
  chartContent: <BASE64 encoded chart content>
  targetNamespace: prometheus
  valuesContent: |
    grafana:
      enabled: false

    alertmanager:
      enabled: false

    defaultRules:
      create: false

    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
  version: 69.8.2
```

</details>
