### ISSUE TITLE
klipper-helm doesn't set HOME env var and tries to write on /

### ISSUE THREAD

**Issue by theodiem** [k3s-io/helm-controller#279]
from the helm-install pod:

```
+ [[ false == \t\r\u\e ]]
+ [[ false == \t\r\u\e ]]
+ [[ -n '' ]]
+ helm_content_decode
+ set -e
+ ENC_CHART_PATH=/chart/kubernetes-replicator.tgz.base64
+ CHART_PATH=/tmp/kubernetes-replicator.tgz
+ [[ ! -f /chart/kubernetes-replicator.tgz.base64 ]]
+ return
+ [[ install != \d\e\l\e\t\e ]]
+ helm_repo_init
+ grep -q -e 'https\?://'
+ [[ kubernetes-replicator/kubernetes-replicator == stable/* ]]
+ [[ -n https://helm.mittwald.de ]]
+ [[ -f /auth/username ]]
+ [[ -f /auth/tls.crt ]]
+ helm repo add kubernetes-replicator https://myhelm.de
Error: mkdir /.config: read-only file system
```
Using `rancher/klipper-helm:v0.9.6-build20250616` and k3s 1.32

**Comment by brandond** [comment]
Are you for some reason using a custom deployment of helm-controller? I can guarantee that the helm-controller built into k3s does not do this.

**Comment by brandond** [comment]
The helm job image runs as user klipper-helm, we shouldn't need to manually set the home dir as a this should come from the passwd entry.

Ref: https://github.com/k3s-io/klipper-helm/blob/404c4497a5746f72101de591b3fd2f7603518299/Dockerfile#L32-L41

**Comment by theodiem** [comment]
> Are you for some reason using a custom deployment of helm-controller, or have you in some way modified the helm job spec or job image?

No. In this case here is the yaml for the helm deployment:
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kubernetes-replicator
  namespace: kube-system
spec:
  jobImage: rancher/klipper-helm:v0.9.6-build20250616
  targetNamespace: system-replicator
  chart: kubernetes-replicator
  repo: https://myhelchartURI
  version: 2.11.1
```

>Its possible something changed in alpine 1.22 but that would be a surprising regression.

Not sure if its alpine, but launching it inside my K3S cluster, HOME is not set as expected:
```
#kubectl run -it --rm helmdebug --image rancher/klipper-helm:v0.9.6-build20250616 --command -- /bin/bash
If you don't see a command prompt, try pressing enter.

helmdebug:/home/klipper-helm$ whoami
klipper-helm

helmdebug:/home/klipper-helm$ getent passwd klipper-helm
klipper-helm:x:1000:1000::/home/klipper-helm:/bin/bash

helmdebug:/home/klipper-helm$ ls -lad ~
drwxr-xr-x    1 root     root            12 Jun 16 19:28 /

helmdebug:/home/klipper-helm$
```
You can see that WORKDIR is correct (since the container started on `/home/klipper-helm`) but you can notice by the PS1 that HOME was not set. Confirmed by the `~` expansion.

If you know the tag of an older image, I'm happy to fire it up (its a ephemeral cluster anyways) to test.
