### ISSUE TITLE
Can't upgrade helm charts after deployment

### ISSUE THREAD

**Issue by brokenjacobs** [k3s-io/helm-controller#32]
I'm using flux to deploy a HelmChart CRD into my k3s setup. The initial deploy works fine, but i update the HelmChart manifest with a new version of a chart the controller doesn't detect this as an upgrade. It attempts to do a new install of the chart, with the same deployment name. Which fails. Using v2 or v3 helm. With:
`Error: cannot re-use a name that is still in use`

Is this a feature that is planned to be added?

**Comment by pulpo** [comment]
Same problem here!

**Comment by ibuildthecloud** [comment]
Can you give an example of a before and after HelmChart CR that fails?

**Comment by ibrokethecloud** [comment]
I suspect issue is the job uses `helm install`, which is perform when the `args` method parses over the helm spec. 

https://github.com/rancher/helm-controller/blob/master/pkg/helm/controller.go#L321

To make it more idempotent, we should probably change the args to `helm upgrade --install`

**Comment by ibrokethecloud** [comment]
I dug around some more.. here is a sample when install is present

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: wordpress
  namespace: default
spec:
  targetNamespace: default
  chart: wordpress
  repo: https://charts.bitnami.com/bitnami
  version: 7.4.0
  set:
    persistence.enabled: "false"
    mariadb.master.persistence.enabled: "false"
  helmVersion: v3
```

Initial install works fine. When I update the manifest to a new version

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: wordpress
  namespace: default
spec:
  targetNamespace: default
  chart: wordpress
  repo: https://charts.bitnami.com/bitnami
  version: 9.0.0
  set:
    persistence.enabled: "false"
    mariadb.master.persistence.enabled: "false"
  helmVersion: v3
```

https://github.com/rancher/klipper-helm/blob/master/entry#L33

I suspect check should be `[ $INSTALLED_VERSION != $VERSION ]` for the upgrade branch to be executed.

Because of equality comparison the code falls through and goes back to the default execution:

https://github.com/rancher/klipper-helm/blob/master/entry#L33

After the tweak, the upgrade works as expected.

```
Already installed wordpress, upgrading
+ echo Already installed wordpress, upgrading
+ shift 1
+ helm_v3 --namespace default --repo https://charts.bitnami.com/bitnami --version 9.0.0 --set mariadb.master.persistence.enabled=false --set persistence.enabled=false upgrade wordpress wordpress
```
