### ISSUE TITLE
Support `valuesContent` from secret

### ISSUE THREAD

**Issue by 0x4c6565** [k3s-io/helm-controller#64]
In some instances, it is necessary to provide secret values to Helm. To aid with secret storage with GitOps, it would be nice to be able to support the supplying of values (either entire `valuesContent` or individual values) via secrets (`secretRef`)

**Comment by brandond** [comment]
Confidential data should not be stored in the chart values, regardless of where those chart values come from. Charts that need to take credentials or other confidential data should (and usually do) allow specifying the name of an existing secret containing the data. That secret can be externally provisioned or managed by a secrets management operator, without having keep ALL the chart options in the secret.

See for example our [vsphere charts](https://github.com/rancher/vsphere-charts/blob/main/charts/rancher-vsphere-csi/values.yaml). You **CAN** pass the vsphere username, password, etc via individual chart values, but this is not recommended. You should instead put those values in a secret, and then set:
```yaml
vCenter:
  configSecret:
    name: my-existing-vsphere-creds-secret
    generate: false 
```

**Comment by brandond** [comment]
If we are going to add support for values from a secret or multiple secrets, there are a few questions to answer.

#### Background:
RKE2 and K3 ship HelmChart resources that are managed by the distro and cannot be modified. If users want to provide their own values they put those values in a HelmChartConfig resource with a matching name, and those values override the HelmChart ValuesContent. We just dump the ValuesContent from both sources into files in the job pod via a secret mount and let Helm’s existing merge logic handle ordering and precedence, based on the order that the files are provided to the CLI.

#### Questions:
1. Do we want to allow setting a ValuesSecret on the HelmChart itself? Or just on the HelmChartConfig? The order is currently (from least to greatest):
`HelmChart ValuesContent -> HelmChartConfig ValuesContent -> HelmChart Set`
My preference would be to allow valuesSecret on both HelmChart and HelmChartConfig, and order them after the current ValuesContent for each.
Where would we like to add Secrets in that order?

2. What do we expect to be in the secret?
My preference would be to have keys in the secret mounted as files in the helm job pod, and values would be the content of each file. This is similar to the current logic for how we mount valuesContent data into the helm job pod. Figuring out how to get everything ordered correctly using this structure might be interesting but I think we can figure it out.

3. Should we support multiple secrets, or just one secret, per HelmChart/HelmChartConfig?
My preference would be to only support a single secret:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesSecret:
    name: my-traefik-chart-secret
  valuesContent: |-
    image:
      name: traefik
      tag: 2.9.10
    ports:
      web:
        forwardedHeaders:
          trustedIPs:
            - 10.0.0.0/8
```
5. Should we support a field under valuesSecret to mark the secret as optional?
4. Do we need to watch the secret for changes, and trigger a `helm upgrade` when the secret changes?
6. What happens if the secret is required but deleted? Does this put the chart into an error state?

**Comment by mattfarina** [comment]
To respond to Brad's questions...

> 1. Do we want to allow setting a ValuesSecret on the HelmChart itself?

I don't have a preference.

> 2. What do we expect to be in the secret?

I think there is a bit of UX to think about here. So, I did a little digging at what's elsewhere for comparison.

[Fleet](https://fleet.rancher.io/) provides a means to specify this in the [`fleet.yaml`](https://fleet.rancher.io/ref-fleet-yaml) file. The section looks like:

```yaml
  valuesFrom:
    - secretKeyRef:
        name: secret-values
        namespace: default
        key: values.yaml
```

Fleet offers a ConfigMap option (not in the example) that I would not recommend doing. There is no benefit over the current CR.

This style does provide the ability to be mounted as a file.

[Flux](https://fluxcd.io/) has a `valuesFrom` key on the spec for the `HelmRelease` resource.  It looks like...

```yaml
valuesFrom:
  - configMapKeyRef:
      name: my-config-values
      namespace: my-ns
      key: values.yaml
      optional: false
  - secretKeyRef:
      name: my-secret-values
      namespace: my-ns
      key: values.yaml
      optional: true
```

I've left the ConfigMap option in just for an example of the options. It's the same as Fleet, even for the configmap option. [Here's a description of the fields](https://pkg.go.dev/github.com/fluxcd/pkg/apis/meta?#ValuesReference).

It appears Argo does not have support for this type of functionality and I've found examples of end users working around it. The UX around these is not elegant.

A key that accepts a slice of name/key seems fairly straight forward and could be used for mounting the secret as a file and then calling files that have been mounted. You'll notice I dropped the namespace key. If the secret is in a different namespace from the helm-controller CRs that reference it, how would we check for proper access to those namespaces? The Flux controller dropped support for namespace.

> 3. Should we support multiple secrets, or just one secret, per HelmChart/HelmChartConfig?

I went looking to see what users of other projects did. I found that a mass majority of the cases were a single referenced object. But, there were multiple cases where multiple ConfigMaps or Secrets were used.

Should there be multiple now to avoid the request in the future?

> 4. Should we support a field under valuesSecret to mark the secret as optional?

By optional, I'm assuming you mean that when the secrets not present it the chart is still installed. Flux has this. Not a bad idea.

> 5. Do we need to watch the secret for changes, and trigger a helm upgrade when the secret changes?

I'm ok if there is no watch on the Secret. There are ways to work around that.

> 6. What happens if the secret is required but deleted? Does this put the chart into an error state?

The next time there is a change to the CR which would start a pod to run Helm you get an error because the secret is not present. This could be returned as a status and the pod is never started. Would this work?

> 7. Do we need to support setting individual values (by dotted --set style path) from multiple secrets/keys, as requested in the initial comment?

I don't think we need this. Keep it simple.

Hope my 2 cents helps.

**Comment by mattfarina** [comment]
Note, the reason I'm jumping into this issue is because...

* k3s users do use helm-controller to install their own charts
* They don't always control those charts, sometimes they come from 3rd parties, and those charts may not have the ability to specify a secret for private information (e.g., user/pass).
* Fleet, Flux, and Argo users all have a solution to this situation. In the case of argo, it looks like it was the community of users who solved for it. The Argo situation illustrates the need is real and users have worked around the shortcoming.

I would suggest there is a real need for this. There is this issue, so someone here noticed.

**Comment by brandond** [comment]
Lets adapt Fleet's support for multiple, but instead of allowing multiple types in the valuesFrom lets just allow a list of secret key/name pairs. Each ref uses the value of a single key in a secret as a values file. This appears to allow cross-namespace references, which I would NOT like to support. I'd like to enforce that the secret be in the same namespace as the chart.

Something like this:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      name: traefik
      tag: 2.9.10
  valuesSecrets:
    - name: my-first-secret
       key: values.yaml
    - name: my-other-secret
       key: values.yaml
```

I THINK we already have a secret cache wired up, I can see about adding an index to that to kick off changes when the secret changes or is created/deleted.

For now lets make the secrets optional, I think that's easier? If it doesn't exist, or is deleted, it's just ignored. Deleting a secret or removing the key from the secret will kick off a `helm upgrade` to remove the now-missing values.

**Comment by mattfarina** [comment]
That sounds good, except that if the secret is specified but it doesn't exist when Helm is run on the configuration I think there should be an error. I think it would be confusing and possibly destructive if a user specified a secret, it wasn't there, and helm ran on the chart and just ignored the missing values.

Consider the case where you have credentials in the secret and those credentials are used to connect to a database. When the secret is missing the credentials are not present for the app. So, it starts up, cannot connect to the database, and the app is unable to operate properly and users aren't going to see an obvious reference as to why. I suspect this is why flux has the `optional` property.

**Comment by brandond** [comment]
OK. Lets add an Optional field then for parity.

We do something similar with `spec.secrets` for System Upgrade Controller - you can set `IgnoreUpdates: true` on a secret ref and the secret becomes optional, and changes to it do not trigger a re-run of the plan.

**Comment by mdrahman-suse** [comment]
# Validation with v1.32.4-rc1+k3s1, v1.31.8-rc1+k3s1, v1.30.12-rc1+k3s1

- hc.yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: apache
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: apache
  valuesSecrets:
  - name: apache-chart-values
    keys:
    - values1.yaml
    - values2.yaml  
  - name: apache-chart-more-values
    keys:
    - values.yaml
    ignoreUpdates: true
---
apiVersion: v1
kind: Secret
metadata:
  name: apache-chart-values
type: Opaque
stringData:
  values1.yaml: |-
    service:
      type: ClusterIP
    ingress:
      enabled: true
  values2.yaml: |-
    ingress:
      hostname: www.example.com
    networkPolicy:
      enabled: false
```

### Testing
- Install k3s 
- Deploy hc.yaml
- Ensure the deployment succeeds
### Replication
```
~> k3s -v
k3s version v1.32.3+k3s1 (079ffa8d)
go version go1.23.6
```
```
kubectl apply -f hc.yaml
secret/apache-chart-values created
Error from server (BadRequest): error when creating "hm.yaml": HelmChart in version "v1" cannot be handled as a HelmChart: strict decoding error: unknown field "spec.valuesSecrets"
```
### Validation
```
k3s -v
k3s version v1.32.4-rc1+k3s1 (6b330558)
go version go1.23.6
```
```
kubectl apply -f hc.yaml
helmchart.helm.cattle.io/apache created
secret/apache-chart-values created
```

<img width="402" alt="Image" src="https://github.com/user-attachments/assets/b319978c-e820-43b3-9619-a5b3b90cf4b7" />
